import {
  createMessage,
  isApplicationMessagePayload,
  isRecord,
  messageTypes,
  parseMessage,
  requiredString,
  serializeMessage,
  type ApplicationMessagePayload,
  type ConnectAcceptedPayload,
  type ConnectRejectedPayload,
  type ConnectRequestPayload,
  type DisconnectPayload,
  type HeartbeatPayload,
  type ProtocolEnvelope,
  type ResumeAcceptedPayload,
  type ResumeRejectedPayload,
  type ResumeRequestPayload,
} from "./protocol.js";
import {
  assertCompatibleConnectionDescriptor,
  createConnectionDescriptor,
  type ConnectionDescriptor,
} from "./connection-descriptor.js";
import {
  createDefaultIdentityStore,
  type PeerIdentityStore,
} from "./identity.js";

export type ConnectionState = "idle" | "connecting" | "connected" | "reconnecting" | "closing" | "closed";

export interface ConnectionInfo {
  connectionId: string;
  peerId?: string;
  resumeToken?: string;
}

export interface PartyGameClientEvents {
  state: ConnectionState;
  applicationMessage: ApplicationMessagePayload;
  message: ProtocolEnvelope;
  rawMessage: MessageEventData;
  error: Error;
}

export type MessageEventData = string | ArrayBuffer | Blob;
export type ClientEventName = keyof PartyGameClientEvents;
export type ClientEventListener<K extends ClientEventName> = (value: PartyGameClientEvents[K]) => void;

export interface WebSocketLike {
  readonly readyState: number;
  binaryType: BinaryType;
  onopen: ((event: Event) => void) | null;
  onmessage: ((event: MessageEvent) => void) | null;
  onclose: ((event: CloseEvent) => void) | null;
  onerror: ((event: Event) => void) | null;
  send(data: string | ArrayBufferLike | Blob | ArrayBufferView): void;
  close(code?: number, reason?: string): void;
}

export interface PartyGameClientOptions {
  /**
   * Stable communication identity used only for resume/reconnect. Pass null for
   * an anonymous connection that does not need continuity. When omitted, a
   * neutral peer id is loaded/generated by the identity store.
   */
  peerId?: string | null;
  identityStore?: PeerIdentityStore;
  webSocketFactory?: (url: string) => WebSocketLike;
  messageIdFactory?: () => string;
  heartbeatIntervalMs?: number;
  reconnectDelayMs?: number;
  autoReconnect?: boolean;
}

export class ConnectionRejectedError extends Error {
  public constructor(public readonly rejection: ConnectRejectedPayload | ResumeRejectedPayload) {
    super(rejection.reason ?? rejection.code);
    this.name = "ConnectionRejectedError";
  }
}

export class PartyGameClient {
  private readonly identityStore: PeerIdentityStore;
  private readonly webSocketFactory: (url: string) => WebSocketLike;
  private readonly messageIdFactory: () => string;
  private readonly heartbeatIntervalMs: number;
  private readonly reconnectDelayMs: number;
  private readonly autoReconnect: boolean;
  private readonly configuredPeerId: string | null | undefined;
  private readonly listeners = new Map<ClientEventName, Set<(value: unknown) => void>>();

  private socket: WebSocketLike | null = null;
  private descriptor: ConnectionDescriptor | null = null;
  private connection: ConnectionInfo | null = null;
  private currentState: ConnectionState = "idle";
  private heartbeatHandle: ReturnType<typeof setInterval> | null = null;
  private reconnectHandle: ReturnType<typeof setTimeout> | null = null;
  private pendingConnection: {
    resolve: (connection: ConnectionInfo) => void;
    reject: (reason: unknown) => void;
  } | null = null;
  private intentionallyClosing = false;
  private peerId: string | null = null;

  public constructor(options: PartyGameClientOptions = {}) {
    this.configuredPeerId = options.peerId;
    this.identityStore = options.identityStore ?? createDefaultIdentityStore();
    this.webSocketFactory = options.webSocketFactory ?? defaultWebSocketFactory;
    this.messageIdFactory = options.messageIdFactory ?? defaultMessageIdFactory;
    this.heartbeatIntervalMs = options.heartbeatIntervalMs ?? 10_000;
    this.reconnectDelayMs = options.reconnectDelayMs ?? 1_000;
    this.autoReconnect = options.autoReconnect ?? true;
    if (this.configuredPeerId !== null && this.configuredPeerId !== undefined) {
      requiredString(this.configuredPeerId, "peerId");
    }
    if (this.heartbeatIntervalMs <= 0) throw new Error("heartbeatIntervalMs must be positive");
    if (this.reconnectDelayMs < 0) throw new Error("reconnectDelayMs cannot be negative");
  }

  public get state(): ConnectionState {
    return this.currentState;
  }

  public get activeConnection(): ConnectionInfo | null {
    return this.connection;
  }

  public get stablePeerId(): string | null {
    return this.peerId;
  }

  public on<K extends ClientEventName>(event: K, listener: ClientEventListener<K>): () => void {
    let listeners = this.listeners.get(event);
    if (listeners === undefined) {
      listeners = new Set();
      this.listeners.set(event, listeners);
    }
    listeners.add(listener as (value: unknown) => void);
    return () => listeners?.delete(listener as (value: unknown) => void);
  }

  public async connect(descriptor: ConnectionDescriptor): Promise<ConnectionInfo> {
    if (this.pendingConnection !== null || this.socket !== null) {
      throw new Error("Client is already connecting or connected");
    }
    const normalized = createConnectionDescriptor(descriptor);
    assertCompatibleConnectionDescriptor(normalized);
    this.descriptor = normalized;
    this.intentionallyClosing = false;
    this.connection = null;
    this.peerId = this.resolvePeerId();
    return this.openSocket(false);
  }

  public async reconnect(): Promise<ConnectionInfo> {
    if (this.descriptor === null) throw new Error("Cannot reconnect before connect()");
    if (this.socket !== null) throw new Error("Client is already connected");
    if (this.peerId === null) throw new Error("Anonymous connections cannot resume");
    const credential = this.identityStore.getResumeCredential(this.resumeScope(this.descriptor));
    if (credential === null) throw new Error("No resume credential is available");
    this.intentionallyClosing = false;
    return this.openSocket(true);
  }

  public disconnect(reason?: string, clearResumeCredential = false): void {
    this.intentionallyClosing = true;
    this.cancelReconnect();
    this.stopHeartbeat();
    const socket = this.socket;
    if (socket !== null && socket.readyState === 1) {
      const payload: DisconnectPayload = reason === undefined ? {} : { reason: requiredString(reason, "reason") };
      socket.send(serializeMessage(createMessage(messageTypes.disconnect, this.messageIdFactory(), payload)));
    }
    if (clearResumeCredential && this.descriptor !== null) {
      this.identityStore.clearResumeCredential(this.resumeScope(this.descriptor));
    }
    this.setState("closing");
    socket?.close(1000, "client-disconnect");
    this.socket = null;
    this.connection = null;
    this.setState("closed");
  }

  public send<TData>(applicationType: string, data: TData, correlationId?: string): string {
    if (this.socket === null || this.socket.readyState !== 1 || this.connection === null) {
      throw new Error("Client is not connected");
    }
    const messageId = this.messageIdFactory();
    const payload: ApplicationMessagePayload<TData> = {
      applicationType: requiredString(applicationType, "applicationType"),
      data,
    };
    this.socket.send(serializeMessage(createMessage(
      messageTypes.applicationMessage,
      messageId,
      payload,
      correlationId,
    )));
    return messageId;
  }

  public sendRaw(data: string | ArrayBufferLike | Blob | ArrayBufferView): void {
    if (this.socket === null || this.socket.readyState !== 1 || this.connection === null) {
      throw new Error("Client is not connected");
    }
    this.socket.send(data);
  }

  private openSocket(forceResume: boolean): Promise<ConnectionInfo> {
    const descriptor = this.descriptor;
    if (descriptor === null) throw new Error("Connection descriptor is unavailable");

    const credential = this.peerId === null
      ? null
      : this.identityStore.getResumeCredential(this.resumeScope(descriptor));
    const shouldResume = credential !== null && credential.peerId === this.peerId;
    if (forceResume && !shouldResume) throw new Error("No matching resume credential is available");

    this.setState(forceResume || shouldResume ? "reconnecting" : "connecting");
    const socket = this.webSocketFactory(descriptor.endpoint);
    socket.binaryType = "arraybuffer";
    this.socket = socket;

    const result = new Promise<ConnectionInfo>((resolve, reject) => {
      this.pendingConnection = { resolve, reject };
    });

    socket.onopen = () => {
      if (shouldResume && credential !== null) {
        const payload: ResumeRequestPayload = {
          peerId: credential.peerId,
          resumeToken: credential.resumeToken,
        };
        socket.send(serializeMessage(createMessage(messageTypes.resumeRequest, this.messageIdFactory(), payload)));
        return;
      }

      const payload: ConnectRequestPayload = this.peerId === null ? {} : { peerId: this.peerId };
      socket.send(serializeMessage(createMessage(messageTypes.connectRequest, this.messageIdFactory(), payload)));
    };

    socket.onmessage = (event) => void this.handleIncoming(event.data);
    socket.onerror = () => this.emit("error", new Error("WebSocket transport error"));
    socket.onclose = (event) => this.handleClose(event);
    return result;
  }

  private async handleIncoming(data: unknown): Promise<void> {
    const messageData = await normalizeMessageData(data);
    if (messageData === null) return;

    let envelope: ProtocolEnvelope;
    try {
      const protocolInput = messageData instanceof Blob ? await messageData.arrayBuffer() : messageData;
      envelope = parseMessage(protocolInput);
    } catch {
      this.emit("rawMessage", messageData);
      return;
    }

    try {
      switch (envelope.type) {
        case messageTypes.connectAccepted:
          this.acceptConnect(envelope.payload);
          break;
        case messageTypes.resumeAccepted:
          this.acceptResume(envelope.payload);
          break;
        case messageTypes.connectRejected:
          this.rejectConnection(envelope.payload as ConnectRejectedPayload);
          break;
        case messageTypes.resumeRejected:
          this.rejectConnection(envelope.payload as ResumeRejectedPayload);
          break;
        case messageTypes.applicationMessage:
          if (!isApplicationMessagePayload(envelope.payload)) {
            throw new Error("Invalid application message payload");
          }
          this.emit("applicationMessage", envelope.payload);
          break;
        default:
          this.emit("message", envelope);
          break;
      }
    } catch (error) {
      this.emit("error", asError(error));
    }
  }

  private acceptConnect(value: unknown): void {
    if (!isConnectAcceptedPayload(value)) throw new Error("Invalid connect accepted payload");
    if (this.peerId !== null && value.peerId !== undefined && value.peerId !== this.peerId) {
      throw new Error("Connection was accepted for a different peer identity");
    }
    if (value.peerId !== undefined) {
      this.peerId = value.peerId;
      this.identityStore.setPeerId(value.peerId);
    }
    this.storeResumeCredential(value.peerId, value.resumeToken);
    this.connection = {
      connectionId: value.connectionId,
      ...(value.peerId === undefined ? {} : { peerId: value.peerId }),
      ...(value.resumeToken === undefined ? {} : { resumeToken: value.resumeToken }),
    };
    this.completeConnection();
  }

  private acceptResume(value: unknown): void {
    if (!isResumeAcceptedPayload(value)) throw new Error("Invalid resume accepted payload");
    if (this.peerId === null || value.peerId !== this.peerId) {
      throw new Error("Resume was accepted for an unexpected peer identity");
    }
    this.storeResumeCredential(value.peerId, value.resumeToken);
    this.connection = {
      connectionId: value.connectionId,
      peerId: value.peerId,
      ...(value.resumeToken === undefined ? {} : { resumeToken: value.resumeToken }),
    };
    this.completeConnection();
  }

  private completeConnection(): void {
    const connection = this.connection;
    if (connection === null) return;
    this.cancelReconnect();
    this.setState("connected");
    this.startHeartbeat();
    this.pendingConnection?.resolve(connection);
    this.pendingConnection = null;
  }

  private rejectConnection(payload: ConnectRejectedPayload | ResumeRejectedPayload): void {
    const error = new ConnectionRejectedError(payload);
    if (this.descriptor !== null && "peerId" in payload) {
      this.identityStore.clearResumeCredential(this.resumeScope(this.descriptor));
    }
    this.pendingConnection?.reject(error);
    this.pendingConnection = null;
    this.emit("error", error);
    this.intentionallyClosing = true;
    this.socket?.close(1008, "connection-rejected");
    this.socket = null;
    this.setState("closed");
  }

  private handleClose(event: CloseEvent): void {
    this.stopHeartbeat();
    this.socket = null;
    this.connection = null;
    if (this.pendingConnection !== null) {
      this.pendingConnection.reject(new Error(`WebSocket closed before connection completed (${event.code})`));
      this.pendingConnection = null;
    }
    if (this.intentionallyClosing || !this.autoReconnect || this.descriptor === null || this.peerId === null) {
      this.setState("closed");
      return;
    }
    const credential = this.identityStore.getResumeCredential(this.resumeScope(this.descriptor));
    if (credential === null) {
      this.setState("closed");
      return;
    }
    this.setState("reconnecting");
    this.cancelReconnect();
    this.reconnectHandle = setTimeout(() => {
      this.reconnectHandle = null;
      void this.openSocket(true).catch((error) => this.emit("error", asError(error)));
    }, this.reconnectDelayMs);
  }

  private startHeartbeat(): void {
    this.stopHeartbeat();
    this.heartbeatHandle = setInterval(() => {
      const socket = this.socket;
      if (socket === null || this.connection === null || socket.readyState !== 1) return;
      const payload: HeartbeatPayload = this.peerId === null ? {} : { peerId: this.peerId };
      socket.send(serializeMessage(createMessage(messageTypes.heartbeat, this.messageIdFactory(), payload)));
    }, this.heartbeatIntervalMs);
  }

  private stopHeartbeat(): void {
    if (this.heartbeatHandle !== null) {
      clearInterval(this.heartbeatHandle);
      this.heartbeatHandle = null;
    }
  }

  private cancelReconnect(): void {
    if (this.reconnectHandle !== null) {
      clearTimeout(this.reconnectHandle);
      this.reconnectHandle = null;
    }
  }

  private resolvePeerId(): string | null {
    if (this.configuredPeerId === null) return null;
    if (this.configuredPeerId !== undefined) return requiredString(this.configuredPeerId, "peerId");
    const existing = this.identityStore.getPeerId();
    if (existing !== null && existing.trim().length > 0) return existing;
    const generated = `peer-${randomId()}`;
    this.identityStore.setPeerId(generated);
    return generated;
  }

  private resumeScope(descriptor: ConnectionDescriptor): string {
    return descriptor.channelId === undefined
      ? `${descriptor.transport}:${descriptor.endpoint}`
      : `${descriptor.transport}:channel:${descriptor.channelId}`;
  }

  private storeResumeCredential(peerId: string | undefined, resumeToken: string | undefined): void {
    if (peerId === undefined || resumeToken === undefined || this.descriptor === null) return;
    this.identityStore.setResumeCredential({
      scope: this.resumeScope(this.descriptor),
      peerId,
      resumeToken,
    });
  }

  private setState(state: ConnectionState): void {
    if (this.currentState === state) return;
    this.currentState = state;
    this.emit("state", state);
  }

  private emit<K extends ClientEventName>(event: K, value: PartyGameClientEvents[K]): void {
    for (const listener of this.listeners.get(event) ?? []) listener(value);
  }
}

function isConnectAcceptedPayload(value: unknown): value is ConnectAcceptedPayload {
  return isRecord(value) &&
    typeof value.connectionId === "string" && value.connectionId.trim().length > 0 &&
    (value.peerId === undefined || (typeof value.peerId === "string" && value.peerId.trim().length > 0)) &&
    (value.resumeToken === undefined || (typeof value.resumeToken === "string" && value.resumeToken.trim().length > 0));
}

function isResumeAcceptedPayload(value: unknown): value is ResumeAcceptedPayload {
  return isRecord(value) &&
    typeof value.connectionId === "string" && value.connectionId.trim().length > 0 &&
    typeof value.peerId === "string" && value.peerId.trim().length > 0 &&
    (value.resumeToken === undefined || (typeof value.resumeToken === "string" && value.resumeToken.trim().length > 0));
}

async function normalizeMessageData(data: unknown): Promise<MessageEventData | null> {
  if (typeof data === "string" || data instanceof ArrayBuffer || data instanceof Blob) return data;
  if (ArrayBuffer.isView(data)) {
    return data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength) as ArrayBuffer;
  }
  return null;
}

function defaultWebSocketFactory(url: string): WebSocketLike {
  return new WebSocket(url);
}

function defaultMessageIdFactory(): string {
  return typeof globalThis.crypto?.randomUUID === "function" ? globalThis.crypto.randomUUID() : randomId();
}

function randomId(): string {
  return Math.random().toString(36).slice(2) + Date.now().toString(36);
}

function asError(error: unknown): Error {
  return error instanceof Error ? error : new Error(String(error));
}
