<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Versioned communication control protocol and connection descriptors for Dihor.GameKit.Networking.</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Dihor.GameKit.Networking.Core/Dihor.GameKit.Networking.Core.csproj" />
  </ItemGroup>
</Project>
